# Generated by Django 5.0.6 on 2024-06-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_rename_created_at_tweets_posted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='updated_at',
        ),
    ]
