# Generated by Django 5.0.6 on 2024-06-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_remove_tweets_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='pfp',
            field=models.ImageField(blank=True, default='defaults/male.jpg', null=True, upload_to=''),
        ),
    ]
