# Generated by Django 5.0.6 on 2024-06-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_tweets_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='pfp',
        ),
        migrations.AddField(
            model_name='tweets',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
