# Generated by Django 5.0.6 on 2024-06-11 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
