# Generated by Django 5.0.6 on 2024-06-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0016_alter_tweets_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
