# Generated by Django 5.0.6 on 2024-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0022_alter_tweets_tweet_alter_tweets_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='tweet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
