# Generated by Django 5.0.6 on 2024-06-13 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0023_alter_tweets_tweet_alter_tweets_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='user',
        ),
        migrations.AddField(
            model_name='tweets',
            name='profile',
            field=models.ForeignKey(default=0.00024703557312252963, on_delete=django.db.models.deletion.CASCADE, to='logic.profile'),
            preserve_default=False,
        ),
    ]
