# Generated by Django 5.0.6 on 2024-06-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0025_tweets_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
