# Generated by Django 5.0.6 on 2024-06-14 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0027_tweets_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='current_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
